const classData = [
    {id: 0, isOpen: true, name: 'CONNECTION', length: "45 or 60 minutes", intensity: "low impact with a moderate challenge", you_will_feel: "well connected in your centre. this feeling will last a couple of days. our suggested remedy is more of this class.", description: 'Our deep core stability sequence at a pace you can follow. this is the place to build strength and ground yourself from the inside out. learn how to identify your body’s weak link, and rehabilitate old or reoccurring injuries, strains or unnecessary tensions.'},
    {id: 1, isOpen: false, name: 'BALANCE', length: "60 minutes", intensity: "moderate to high", you_will_feel: "well and truly connected. both upper and lower body will feel elevated along with a strong sense of awareness for your pelvis, shoulders & spine.", description: 'Our whole body class. we grow from the foundation set in CONNECTION. a quicker pace, with upper and lower body involved in new planes, dimensions and shapes. we continue to emphasize stability, as this is the building block for fluid movement.'},
    {id: 2, isOpen: false,  name: 'SPIRIT', length: "60 to 75 minutes", intensity: "low to moderate", you_will_feel: "relaxed, recharged and ready to ease into your day.", description: 'A slow, deliberate way to introduce stretching to your established foundation from CONNECTION + BALANCE. this class is a beautiful additional layer for anyone looking to add fluid movement to their understanding of our deep core stability work.'},
    {id: 3, isOpen: false,  name: 'FREEDOM', length: "60 minutes", intensity: "moderate to high", you_will_feel: "heat being built, awareness being stoked and a glisten on your brow.", description: 'building on the stability and fluidity created by CONNECTION, BALANCE + SPIRIT; be prepared to move at your breaths pace and piece together purposeful sequencing that feels enjoyable. we all need a little FREEDOM.'},
    {id: 4, isOpen: false,  name: 'FUSION', length: "45 minutes", intensity: "very high", you_will_feel: "elevation in your heart rate, all while enjoying the wild ride.", description: ' this class will test your stability, fluidity and ability to keep up with the pace. it’s the icing on your technical foundation. learn to support your body, find balance and connect to your power in standing postures. this intricate sequencing will blend CONNECTION, BALANCE, SPIRIT + FREEDOM with a wild twist.'},
    {id: 5, isOpen: false,  name: 'SYNTHESIS', length: "60 minutes", intensity: "next level", you_will_feel: "this is the culmination. it’s everything you felt you needed, and now have experienced.", description: 'the final combination of elements; CONNECTION, BALANCE, SPIRIT, FREEDOM, FUSION. you are the forming of a more complex substance from these simpler compounds. when you know, you know.'}
]

export default classData
